services:
  silo:
    container_name: ${COMPOSE_PROJECT_NAME:-project}-silo-container
    image: ${COMPOSE_PROJECT_NAME:-project}-silo
    build:
      context: .
      dockerfile: silo.Dockerfile
    tty: true
    stdin_open: true
    stop_grace_period: 0s
    volumes:
      - .:/home/ubuntu/workspace
